# pacman.conf for Tekipaki OS archiso profile

[options]
HoldPkg     = pacman glibc
IgnorePkg   = linux linux-headers
Architecture = auto
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# [tekipaki]
# SigLevel = Optional TrustAll
# Server = https://github.com/tekipaki-os/packages/releases/download/v1.6/
