---
# Users module configuration
defaultGroups:
    - lp
    - video
    - audio
    - optical
    - storage
    - scanner
    - wheel
    - power
autologinDefault: true
emptyPasswordAllowed: true
sudoersGroup: wheel
setRootPassword: true
doNotSetPassword: false
